// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-EtX-r7mCFOtIdREZoOsLfPr-werbNL4',
    appId: '1:661786963114:web:6116e12e644a869e7174d3',
    messagingSenderId: '661786963114',
    projectId: 'first-app-6e533',
    authDomain: 'first-app-6e533.firebaseapp.com',
    databaseURL: 'https://first-app-6e533-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-6e533.appspot.com',
    measurementId: 'G-PMX58E29KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUivg5AUH2AvD3CVKc7jVQPyUu4GYr1A',
    appId: '1:661786963114:android:0c1c318c17a93bc97174d3',
    messagingSenderId: '661786963114',
    projectId: 'first-app-6e533',
    databaseURL: 'https://first-app-6e533-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-6e533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyZp1VHXZB2oNWULofWkP9FDMG4c46n0',
    appId: '1:661786963114:ios:bb6dfe1443b2cc9b7174d3',
    messagingSenderId: '661786963114',
    projectId: 'first-app-6e533',
    databaseURL: 'https://first-app-6e533-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-6e533.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyZp1VHXZB2oNWULofWkP9FDMG4c46n0',
    appId: '1:661786963114:ios:65fbadacf51f18bb7174d3',
    messagingSenderId: '661786963114',
    projectId: 'first-app-6e533',
    databaseURL: 'https://first-app-6e533-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-6e533.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
